In [193]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor

# The path to our CSV file
file = "Sample/sample.csv"

# Read our Kickstarter data into pandas
sample_df = pd.read_csv(file)
sample_df.head()

,Unnamed: 0,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
0,0,tt0343135,...E alla fine arriva Polly,Along Came Polly,2004,2004-03-12,"Comedy, Romance",90,USA,"English, Spanish",...,5.8,15884.0,5.9,2657.0,5.6,518.0,5.9,26267.0,5.9,61434.0
1,1,tt2180411,Into the Woods,Into the Woods,2014,2015-04-02,"Adventure, Comedy, Drama",125,USA,English,...,6.0,16907.0,6.3,3674.0,5.5,490.0,6.3,21496.0,5.8,49608.0
2,2,tt2304933,La quinta onda,The 5th Wave,2016,2016-02-04,"Action, Adventure, Sci-Fi",112,"USA, UK",English,...,5.5,6609.0,5.7,1536.0,4.8,411.0,5.3,9497.0,5.1,40802.0
3,3,tt1430132,Wolverine - L'immortale,The Wolverine,2013,2013-07-25,"Action, Adventure, Sci-Fi",126,"USA, UK","English, Japanese",...,6.6,20757.0,6.9,4211.0,6.5,697.0,6.8,51630.0,6.6,179707.0
4,4,tt1915581,Magic Mike,Magic Mike,2012,2012-09-21,"Comedy, Drama",110,USA,English,...,6.0,22424.0,6.1,4530.0,5.4,474.0,6.1,22304.0,6.0,58312.0

In [346]:
sample_df.columns

Index(['Unnamed: 0', 'imdb_title_id', 'title', 'original_title', 'year',
       'date_published', 'genre', 'duration', 'country', 'language',
       'director', 'writer', 'production_company', 'actors', 'description',
       'avg_vote', 'votes', 'budget', 'usa_gross_income',
       'worlwide_gross_income', 'metascore', 'reviews_from_users',
       'reviews_from_critics', 'weighted_average_vote', 'total_votes',
       'mean_vote', 'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7',
       'votes_6', 'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

In [347]:
sample_df['original_title'].value_counts()

The Lion King                     10
Halloween                          9
Under the Tuscan Sun               9
Multiple Sarcasms                  9
Escape Room                        8
                                  ..
Book of Shadows: Blair Witch 2     1
Jojo Rabbit                        1
No Reservations                    1
Hugo                               1
Pet Sematary                       1
Name: original_title, Length: 3785, dtype: int64

In [348]:
sample_df.loc[sample_df['original_title']=='Under the Tuscan Sun']

,Unnamed: 0,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
477,477,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
1248,1248,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
2314,2314,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
4647,4647,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
5035,5035,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
5943,5943,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
6548,6548,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
8860,8860,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0
8909,8909,tt0328589,Sotto il sole della Toscana,Under the Tuscan Sun,2003,2004-05-07,"Comedy, Drama, Romance",113,"USA, Italy","English, Italian, Polish, French, Spanish, German",...,7.0,10514.0,7.3,3371.0,6.3,331.0,6.8,10550.0,6.7,20757.0

In [349]:
sample_df['genre'].tolist()

['Comedy, Romance',
 'Adventure, Comedy, Drama',
 'Action, Adventure, Sci-Fi',
 'Action, Adventure, Sci-Fi',
 'Comedy, Drama',
 'Adventure, Comedy, Crime',
 'Comedy',
 'Action, Adventure, Drama',
 'Action, Adventure, Comedy',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Romance',
 'Adventure, Sci-Fi',
 'Crime, Drama, Mystery',
 'Horror, Thriller',
 'Action, Adventure, Sci-Fi',
 'Action, Adventure, Drama',
 'Drama, Fantasy, Romance',
 'Action, Comedy, Crime',
 'Comedy, Drama, Romance',
 'Action, Crime, Thriller',
 'Comedy, Drama, Romance',
 'Action, Adventure, Crime',
 'Fantasy, Horror, Mystery',
 'Comedy, Romance',
 'Horror, Thriller',
 'Biography, Drama',
 'Adventure, Comedy, Sci-Fi',
 'Animation, Comedy, Family',
 'Animation, Adventure, Family',
 'Comedy, Drama, Horror',
 'Comedy',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Animation, Adventure, Family',
 'Comedy, Drama, Music',
 'Action, Thriller',
 'Biography, Comedy, Crime',
 'Action, Drama, Family',
 'Drama',
 'Comedy, Romance',
 'Drama',
 'Drama, Romance',
 'Action, Adventure, Comedy',
 'Action, Adventure, Comedy',
 'Adventure, Comedy, Crime',
 'Drama, Romance',
 'Comedy, Romance, Drama',
 'Crime, Drama, Thriller',
 'Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Horror',
 'Mystery, Thriller',
 'Drama, Family',
 'Drama',
 'Action, Sci-Fi',
 'Action, Adventure, Comedy',
 'Biography, Drama, History',
 'Comedy, Drama',
 'Comedy',
 'Horror, Mystery, Thriller',
 'Drama, Musical',
 'Horror, Thriller',
 'Horror, Thriller',
 'Biography, Drama',
 'Drama, Musical',
 'Action, Adventure, Fantasy',
 'Action, Crime, Drama',
 'Horror, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Romance',
 'Comedy, Sport',
 'Comedy, Drama',
 'Horror, Thriller',
 'Action, Biography, Drama',
 'Horror, Thriller',
 'Animation, Action, Adventure',
 'Horror, Thriller',
 'Action, Crime, Thriller',
 'Animation, Action, Adventure',
 'Drama, Romance',
 'Comedy, Drama',
 'Action, Adventure, Drama',
 'Action, Crime, Thriller',
 'Horror, Mystery, Thriller',
 'Comedy, Crime, Thriller',
 'Comedy',
 'Crime, Drama, Thriller',
 'Action, Crime, Thriller',
 'Comedy, Crime, Drama',
 'Adventure, Drama, Fantasy',
 'Drama, Musical, Romance',
 'Action, Adventure, Sci-Fi',
 'Action, Adventure, Fantasy',
 'Action, Sci-Fi',
 'Biography, Drama, History',
 'Action, Adventure',
 'Action, Drama, Romance',
 'Drama, Romance',
 'Crime, Mystery, Thriller',
 'Horror, Mystery, Sci-Fi',
 'Action, Adventure, Fantasy',
 'Drama, War',
 'Comedy',
 'Animation, Adventure, Comedy',
 'Comedy, Drama, Mystery',
 'Action, Adventure, Fantasy',
 'Action, Thriller',
 'Comedy, Drama, Romance',
 'Action, Drama, Mystery',
 'Comedy',
 'Horror, Mystery, Thriller',
 'Animation, Action, Adventure',
 'Crime, Drama, Thriller',
 'Comedy',
 'Action, Drama, Sport',
 'Drama, Fantasy, Horror',
 'Comedy, Drama, Romance',
 'Comedy, History, Musical',
 'Drama, Romance, War',
 'Drama, Romance',
 'Comedy, Drama, Romance',
 'Biography, Crime, Drama',
 'Horror',
 'Comedy, Romance',
 'Biography, Drama',
 'Drama, History, War',
 'Action, Adventure, Fantasy',
 'Drama, Sport',
 'Comedy',
 'Action, Crime, Thriller',
 'Animation, Action, Adventure',
 'Drama, Musical, Romance',
 'Crime, Drama, Thriller',
 'Drama, Thriller',
 'Horror, Thriller',
 'Comedy, Crime, Drama',
 'Comedy, Drama',
 'Action, Comedy, Crime',
 'Action, Fantasy, Horror',
 'Animation, Adventure, Drama',
 'Horror, Mystery, Thriller',
 'Drama',
 'Comedy, Drama',
 'Adventure, Biography, Drama',
 'Crime, Romance, Thriller',
 'Comedy, Drama, Romance',
 'Comedy, Romance',
 'Action, Thriller',
 'Biography, Drama, Music',
 'Biography, Drama, Sport',
 'Comedy, Drama, Romance',
 'Crime, Drama, Thriller',
 'Horror, Musical, Sci-Fi',
 'Adventure, Comedy, Family',
 'Drama, Romance',
 'Action, Drama, History',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Drama',
 'Comedy, Crime, Drama',
 'Animation, Adventure, Comedy',
 'Comedy, Drama',
 'Horror, Sci-Fi, Thriller',
 'Comedy, Drama',
 'Biography, Drama, History',
 'Biography, Drama',
 'Animation, Adventure, Comedy',
 'Comedy, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Thriller',
 'Comedy',
 'Comedy, Horror',
 'Animation, Adventure, Family',
 'Action, Adventure, Fantasy',
 'Action, Adventure, Family',
 'Biography, Drama',
 'Mystery, Romance, Thriller',
 'Comedy, Drama, Romance',
 'Biography, Drama, Music',
 'Crime, Drama, Mystery',
 'Drama, Horror',
 'Drama, War',
 'Comedy, Drama, Musical',
 'Drama, Sci-Fi, Thriller',
 'Comedy, Sci-Fi',
 'Comedy, Drama',
 'Drama, Romance, War',
 'Comedy, Drama, Romance',
 'Action, Adventure, Sci-Fi',
 'Crime, Drama, Romance',
 'Action, Adventure, Family',
 'Comedy, Crime, Romance',
 'Drama, Romance',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Music',
 'Horror, Mystery, Thriller',
 'Adventure, Comedy',
 'Action, Crime, Horror',
 'Sci-Fi, Thriller',
 'Comedy',
 'Action, Adventure, Sci-Fi',
 'Comedy, Romance',
 'Action, Adventure, Thriller',
 'Drama',
 'Horror, Thriller',
 'Action, Sci-Fi',
 'Action, Comedy, Crime',
 'Action, Mystery, Thriller',
 'Drama, Horror, Mystery',
 'Animation, Adventure, Comedy',
 'Action, Adventure, Thriller',
 'Comedy, Drama',
 'Action, Adventure, Horror',
 'Drama, Horror, Mystery',
 'Action, Adventure, Drama',
 'Action, Crime, Drama',
 'Comedy, Horror, Sci-Fi',
 'Action, Thriller',
 'Animation, Adventure, Comedy',
 'Comedy',
 'Comedy, Family, Fantasy',
 'Adventure, Comedy, Family',
 'Biography, Drama, History',
 'Crime, Drama',
 'Biography, Drama, Sport',
 'Biography, Comedy, Drama',
 'Comedy, Romance',
 'Action, Drama, Thriller',
 'Comedy, Romance',
 'Action, Adventure, Sci-Fi',
 'Animation, Adventure, Comedy',
 'Romance, Sci-Fi, Thriller',
 'Biography, Drama, Family',
 'Action, Comedy, Crime',
 'Action, Adventure, Sci-Fi',
 'Drama, Fantasy, Romance',
 'Comedy, Crime, Romance',
 'Comedy, Fantasy, Horror',
 'Drama, History, War',
 'Comedy, Drama',
 'Action, Drama, Horror',
 'Adventure, Family, Fantasy',
 'Horror, Thriller',
 'Adventure, Family, Fantasy',
 'Action, Adventure, Sci-Fi',
 'Animation, Drama, Family',
 'Action, Adventure, Fantasy',
 'Biography, Drama',
 'Crime, Drama, Thriller',
 'Drama, Thriller',
 'Comedy, Fantasy, Horror',
 'Action, Adventure, Comedy',
 'Action, Drama, Western',
 'Drama, Romance',
 'Comedy, Drama, Romance',
 'Action, Drama, Mystery',
 'Horror, Thriller',
 'Adventure, Comedy, Crime',
 'Animation, Action, Adventure',
 'Animation, Adventure, Family',
 'Action, Adventure, Sci-Fi',
 'Comedy, Crime, Mystery',
 'Drama',
 'Crime, Drama, Mystery',
 'Fantasy, Musical, Romance',
 'Comedy, Romance',
 'Drama, Music, Romance',
 'Adventure, Biography, Drama',
 'Action, Comedy, Crime',
 'Action, Adventure, Comedy',
 'Action, Adventure, Sci-Fi',
 'Biography, Drama, Sport',
 'Adventure, Comedy',
 'Crime, Drama',
 'Comedy, Family, Fantasy',
 'Drama, Romance',
 'Comedy, Drama',
 'Horror, Thriller',
 'Action, Drama, Thriller',
 'Drama, Romance, War',
 'Action, Fantasy, Thriller',
 'Action, Adventure, Drama',
 'Biography, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Comedy, Drama',
 'Action, Adventure, Thriller',
 'Action, Comedy, Crime',
 'Animation, Adventure, Comedy',
 'Comedy, Crime',
 'Horror',
 'Action, Adventure, Thriller',
 'Animation, Action, Adventure',
 'Action, Crime, Drama',
 'Action, Crime, Thriller',
 'Drama, Romance',
 'Crime, Drama',
 'Comedy, Drama',
 'Horror',
 'Horror, Thriller',
 'Comedy, Drama',
 'Horror, Mystery, Thriller',
 'Comedy',
 'Animation, Adventure, Comedy',
 'Action, Thriller',
 'Adventure, Comedy, Family',
 'Horror, Thriller',
 'Drama, Thriller',
 'Action, Adventure, Sci-Fi',
 'Horror, Mystery, Thriller',
 'Sci-Fi, Thriller',
 'Comedy, Drama, Romance',
 'Drama',
 'Comedy, Romance',
 'Comedy, Drama, Romance',
 'Drama',
 'Horror, Thriller',
 'Comedy, Romance',
 'Horror, Thriller',
 'Comedy, Drama, Romance',
 'Drama',
 'Drama, Sport',
 'Drama',
 'Comedy, Family, Fantasy',
 'Action, Crime, Sci-Fi',
 'Comedy, Drama, Romance',
 'Action, Adventure, Comedy',
 'Drama, Thriller',
 'Biography, Drama',
 'Adventure, Drama, Family',
 'Crime, Drama, Romance',
 'Action, Adventure, Fantasy',
 'Comedy, Drama',
 'Animation, Comedy, Family',
 'Comedy, Drama',
 'Biography, Comedy, Crime',
 'Action, Adventure, Fantasy',
 'Animation, Adventure, Drama',
 'Action, Adventure, Comedy',
 'Crime, Drama, Thriller',
 'Adventure, Comedy',
 'Drama, History, Romance',
 'Comedy, Drama, Music',
 'Action, Thriller',
 'Crime, Drama, Romance',
 'Animation, Action, Adventure',
 'Adventure, Comedy',
 'Biography, Drama',
 'Fantasy, Horror, Mystery',
 'Horror, Mystery',
 'Biography, Drama',
 'Comedy, Horror',
 'Drama, Mystery, Sci-Fi',
 'Comedy',
 'Horror, Mystery, Sci-Fi',
 'Action, Comedy, Crime',
 'Adventure, Comedy, Family',
 'Action, Adventure, Crime',
 'Comedy, Drama',
 'Drama, Romance',
 'Adventure, Comedy',
 'Action, Adventure, Sci-Fi',
 'Comedy, Musical, Romance',
 'Comedy',
 'Drama, Mystery, Thriller',
 'Animation, Adventure, Comedy',
 'Action, Fantasy, Thriller',
 'Drama',
 'Action, Drama, War',
 'Biography, Drama',
 'Action, Comedy, Romance',
 'Action, Adventure, Thriller',
 'Drama, Music, Musical',
 'Comedy, Drama, Romance',
 'Drama, Romance',
 'Adventure, Biography, Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Musical',
 'Horror, Mystery, Thriller',
 'Action, Comedy, Drama',
 'Adventure, Comedy',
 'Adventure, Comedy, Drama',
 'Drama',
 'Crime, Thriller',
 'Comedy, Drama, Romance',
 'Drama, Horror, Thriller',
 'Action, Adventure, Comedy',
 'Action, Drama, History',
 'Drama, Mystery, Thriller',
 'Comedy, Drama, Romance',
 'Horror, Mystery, Thriller',
 'Action, Crime, Thriller',
 'Fantasy, Horror',
 'Comedy, Crime, Romance',
 'Action, Adventure, Mystery',
 'Comedy, Horror',
 'Action, Adventure, Horror',
 'Drama, Fantasy, Romance',
 'Drama, Music',
 'Drama, Romance, Thriller',
 'Action, Adventure, Comedy',
 'Action, Crime, Drama',
 'Action, Adventure, Fantasy',
 'Comedy',
 'Comedy, Crime, Drama',
 'Animation, Adventure, Comedy',
 'Action, Adventure, Thriller',
 'Comedy, Romance',
 'Biography, Drama, History',
 'Horror, Thriller',
 'Action, Fantasy, Thriller',
 'Comedy, Drama, Romance',
 'Action, Crime, Thriller',
 'Animation, Action, Adventure',
 'Drama, Musical',
 'Biography, Drama, Romance',
 'Action, Adventure, Sci-Fi',
 'Action, Adventure, Drama',
 'Comedy, Crime, Family',
 'Animation, Adventure, Comedy',
 'Crime, Drama',
 'Comedy, Drama, Romance',
 'Comedy, Romance',
 'Animation, Action, Adventure',
 'Action, Adventure, Fantasy',
 'Action, Comedy, Romance',
 'Adventure, Comedy, Family',
 'Comedy, Family, Fantasy',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Comedy, Drama',
 'Animation, Action, Adventure',
 'Drama, Romance',
 'Action, Adventure, Sci-Fi',
 'Action, Crime, Thriller',
 'Drama',
 'Adventure, Biography, Drama',
 'Action, Comedy, Crime',
 'Crime, Drama, Thriller',
 'Comedy, Sci-Fi',
 'Comedy, Crime, Thriller',
 'Drama, Music, Romance',
 'Drama, History, War',
 'Drama, Music, Romance',
 'Drama, Music, Romance',
 'Drama, Mystery',
 'Drama, Romance',
 'Comedy, Drama',
 'Animation, Adventure, Comedy',
 'Action, Adventure, Sci-Fi',
 'Biography, Crime, Drama',
 'Comedy, Romance',
 'Horror, Sci-Fi, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Drama, Romance',
 'Drama, Horror',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Crime, Drama, Film-Noir',
 'Drama',
 'Comedy, Drama, Romance',
 'Biography, Drama, Sport',
 'Horror, Mystery, Sci-Fi',
 'Comedy, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Drama, Music, Romance',
 'Comedy, Sport',
 'Biography, Drama, History',
 'Comedy, Crime',
 'Comedy',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Romance',
 'Drama, Romance',
 'Drama',
 'Thriller',
 'Drama, Fantasy, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Crime, Drama',
 'Action, Comedy, Crime',
 'Crime, Drama, Thriller',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Fantasy, Romance',
 'Comedy, Drama',
 'Comedy',
 'Comedy, Drama, Fantasy',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Action, Drama, History',
 'Action, Comedy, Crime',
 'Mystery, Thriller',
 'Comedy, Drama, Romance',
 'Action, Adventure, Comedy',
 'Comedy, Drama, Musical',
 'Drama, Family, Romance',
 'Comedy, Drama, Romance',
 'Horror, Mystery, Thriller',
 'Comedy, Drama',
 'Drama, Romance, War',
 'Comedy',
 'Comedy, Crime',
 'Crime, Drama, Romance',
 'Crime, Drama, History',
 'Comedy, Drama, Romance',
 'Drama',
 'Comedy, Drama, Musical',
 'Action, Adventure, Fantasy',
 'Action, Comedy, Crime',
 'Action, Crime, Thriller',
 'Drama',
 'Crime, Thriller',
 'Animation, Crime, Drama',
 'Action, Adventure, Horror',
 'Horror, Thriller',
 'Drama, Musical, Romance',
 'Action, Adventure, Comedy',
 'Action, Adventure, Comedy',
 'Comedy',
 'Mystery, Thriller',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Family, Sport',
 'Action, Drama, Mystery',
 'Drama, Thriller',
 'Horror',
 'Comedy, Romance',
 'Action, Thriller',
 'Action, Crime, Horror',
 'Biography, Drama, History',
 'Crime, Drama',
 'Crime, Drama',
 'Comedy, Drama, Sport',
 'Drama',
 'Comedy, Fantasy, Horror',
 'Action, Drama, Sport',
 'Action, Crime, Drama',
 'Comedy',
 'Comedy, Drama, Family',
 'Drama',
 'Comedy, Family',
 'Horror, Thriller',
 'Action, Adventure, Comedy',
 'Comedy, Drama, Romance',
 'Drama',
 'Adventure, Comedy, Family',
 'Drama, Romance',
 'Action, Adventure, Fantasy',
 'Drama',
 'Comedy, Family, Fantasy',
 'Biography, Crime, Drama',
 'Action, Adventure, Comedy',
 'Animation, Adventure, Comedy',
 'Adventure, Drama, Family',
 'Animation, Adventure, Comedy',
 'Drama',
 'Comedy, Romance',
 'Comedy',
 'Horror',
 'Drama',
 'Action, Crime, Sci-Fi',
 'Animation, Adventure, Comedy',
 'Drama',
 'Crime, Drama, Romance',
 'Crime, Drama',
 'Action, Adventure, Fantasy',
 'Horror, Thriller',
 'Comedy, Crime, Drama',
 'Animation, Adventure, Comedy',
 'Horror',
 'Drama, Fantasy, Romance',
 'Comedy, Crime, Drama',
 'Drama, History, Thriller',
 'Comedy, Drama, Romance',
 'Action, Adventure, Romance',
 'Drama',
 'Crime, Drama, Mystery',
 'Drama, War',
 'Action, Drama, History',
 'Crime, Drama, Thriller',
 'Biography, Drama, Music',
 'Horror, Thriller',
 'Comedy, Drama',
 'Adventure, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Sci-Fi',
 'Action, Adventure, Sci-Fi',
 'Comedy, Drama, Romance',
 'Comedy, Sport',
 'Comedy, Drama',
 'Comedy, Drama, Romance',
 'Action, Drama, Mystery',
 'Drama, Sport',
 'Animation, Adventure, Comedy',
 'Comedy, Drama',
 'Action, Crime, Drama',
 'Action, Drama, Romance',
 'Comedy, Crime',
 'Biography, Comedy, Crime',
 'Comedy',
 'Action, Adventure, Comedy',
 'Action, Adventure, Crime',
 'Action, Adventure, Fantasy',
 'Crime, Drama, Mystery',
 'Action, Adventure, Fantasy',
 'Drama, Romance',
 'Comedy',
 'Action, Crime, Thriller',
 'Action, Adventure, Comedy',
 'Crime, Drama, Thriller',
 'Comedy, Crime, Horror',
 'Animation, Comedy, Family',
 'Action, Fantasy, Thriller',
 'Animation, Adventure, Comedy',
 'Comedy, Drama, Romance',
 'Drama, Fantasy, Romance',
 'Action, Adventure, Comedy',
 'Comedy, Romance, Sport',
 'Action, Mystery, Thriller',
 'Comedy, Drama, Romance',
 'Drama, Mystery',
 'Action, Adventure, Sci-Fi',
 'Comedy, Crime, Drama',
 'Biography, Drama, Music',
 'Adventure, Drama, History',
 'Crime, Horror, Thriller',
 'Adventure, Comedy, Music',
 'Action, Adventure, Comedy',
 'Biography, Crime, Drama',
 'Comedy, War',
 'Action, Thriller',
 'Horror, Mystery, Thriller',
 'Biography, Comedy, Drama',
 'Action, Crime, Thriller',
 'Drama, Sport',
 'Comedy, Romance',
 'Crime, Drama',
 'Horror, Thriller',
 'Animation, Adventure, Family',
 'Drama, Romance, Sci-Fi',
 'Horror, Sci-Fi',
 'Action, Adventure, Comedy',
 'Comedy',
 'Drama, Romance',
 'Crime, Drama, Thriller',
 'Action, Adventure, Sci-Fi',
 'Animation, Comedy, Family',
 'Action, Adventure, Drama',
 'Crime, Drama, Thriller',
 'Comedy, Fantasy',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama',
 'Action, Horror, Sci-Fi',
 'Adventure, Comedy, Family',
 'Action, Adventure, Fantasy',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Horror, Mystery, Sci-Fi',
 'Animation, Adventure, Comedy',
 'Fantasy, Horror, Thriller',
 'Action, Comedy, Fantasy',
 'Comedy, Drama, Fantasy',
 'Comedy, Family, Sci-Fi',
 'Drama, Thriller',
 'Action, Crime, Drama',
 'Drama, Romance',
 'Drama, Music',
 'Comedy, Drama, Romance',
 'Action, Sci-Fi',
 'Comedy, Drama',
 'Drama, Music',
 'Comedy, Crime, Mystery',
 'Horror, Thriller',
 'Drama, Music',
 'Animation, Action, Adventure',
 'Drama, Horror, Thriller',
 'Drama, Family, Musical',
 'Biography, Drama, Thriller',
 'Action, Horror, Sci-Fi',
 'Action, Adventure, Fantasy',
 'Drama, Horror, Mystery',
 'Comedy',
 'Action, Adventure, Fantasy',
 'Action, Comedy, Crime',
 'Drama, Romance',
 'Comedy, Drama, Family',
 'Action, Drama, Thriller',
 'Drama, Fantasy, Romance',
 'Action, Comedy, Crime',
 'Action, Adventure, Thriller',
 'Comedy, Family, Fantasy',
 'Action, Adventure, Thriller',
 'Comedy, Crime, Family',
 'Comedy, Crime, Mystery',
 'Action, Adventure, Comedy',
 'Comedy, Horror',
 'Mystery, Thriller',
 'Crime, Drama, Thriller',
 'Horror, Mystery',
 'Comedy, Crime, Drama',
 'Biography, Drama, Romance',
 'Drama, Fantasy, Romance',
 'Comedy, Sci-Fi',
 'Action, Adventure, Fantasy',
 'Drama',
 'Action, Crime, Thriller',
 'Comedy, War',
 'Horror, Thriller',
 'Drama, Horror, Thriller',
 'Action, Adventure, Fantasy',
 'Action, Crime, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Adventure, Horror',
 'Comedy, Crime, Drama',
 'Drama',
 'Comedy, Music',
 'Comedy, Drama, Fantasy',
 'Fantasy, Sci-Fi',
 'Horror, Thriller',
 'Biography, Comedy, Drama',
 'Comedy, Fantasy',
 'Comedy, Family, Fantasy',
 'Action, Adventure, Family',
 'Drama, Romance',
 'Biography, Drama, War',
 'Adventure, Comedy, Family',
 'Comedy, Family',
 'Animation, Adventure, Comedy',
 'Drama',
 'Drama, Music, Romance',
 'Action, Drama, Thriller',
 'Action, Adventure, Fantasy',
 'Action, Adventure, Thriller',
 'Action, Comedy, Crime',
 'Comedy, Drama, Romance',
 'Action, Adventure, Comedy',
 'Comedy',
 'Adventure, Biography, Drama',
 'Biography, Comedy, Drama',
 'Adventure, Comedy',
 'Adventure, Drama, Western',
 'Drama, Family',
 'Comedy, Music',
 'Animation, Adventure, Comedy',
 'Adventure, Comedy, Drama',
 'Action, Comedy, Crime',
 'Action, Drama, Family',
 'Comedy, Crime, Family',
 'Action, Adventure, Fantasy',
 'Horror, Thriller',
 'Comedy',
 'Drama, Horror, Mystery',
 'Comedy, Family, Fantasy',
 'Comedy, Drama, Music',
 'Horror, Mystery, Thriller',
 'Biography, Drama, History',
 'Comedy, Drama, Romance',
 'Crime, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Fantasy, Horror',
 'Animation, Adventure, Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Music',
 'Comedy',
 'Crime, Drama, Mystery',
 'Comedy, Horror, Sci-Fi',
 'Comedy, Crime, Drama',
 'Biography, Drama, War',
 'Comedy, Horror',
 'Drama, Thriller',
 'Animation, Drama, Sci-Fi',
 'Action, Adventure, Sci-Fi',
 'Comedy',
 'Adventure, Comedy, Family',
 'Comedy',
 'Animation, Adventure, Comedy',
 'Drama, History, War',
 'Adventure, Comedy, Family',
 'Comedy, Horror',
 'Comedy, Horror',
 'Comedy, Family',
 'Horror',
 'Action, Comedy, Crime',
 'Drama, Mystery',
 'Animation, Crime, Drama',
 'Comedy, Musical',
 'Horror, Sci-Fi',
 'Comedy, Romance, Sci-Fi',
 'Adventure, Family, Fantasy',
 'Drama',
 'Drama, Sci-Fi, Thriller',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Drama, Romance',
 'Adventure, Comedy',
 'Action, Adventure, Drama',
 'Comedy, Romance',
 'Comedy, Drama, Music',
 'Animation, Comedy, Family',
 'Action, Comedy, Crime',
 'Comedy, Romance',
 'Action, Adventure, Comedy',
 'Action, Drama, Thriller',
 'Action, Adventure, Comedy',
 'Action, Crime, Fantasy',
 'Drama, Horror, Mystery',
 'Comedy, Crime, Drama',
 'Crime, Drama',
 'Comedy, Drama, Romance',

In [350]:
old_df = pd.DataFrame(sample_df.genre.str.split(', ').tolist(), index=sample_df.original_title)
old_df

                           0          1         2
original_title
Along Came Polly      Comedy    Romance      None
Into the Woods     Adventure     Comedy     Drama
The 5th Wave          Action  Adventure    Sci-Fi
The Wolverine         Action  Adventure    Sci-Fi
Magic Mike            Comedy      Drama      None
...                      ...        ...       ...
Wish I Was Here       Comedy      Drama      None
After Earth           Action  Adventure    Sci-Fi
Pet Sematary         Fantasy     Horror  Thriller
Bohemian Rhapsody  Biography      Drama     Music
Begin Again           Comedy      Drama     Music

[10000 rows x 3 columns]

In [351]:
old_df[2].nunique()

20

In [352]:
dummy_df = pd.get_dummies(old_df, columns=[0,1,2])
dummy_df

,0_Action,0_Adventure,0_Animation,0_Biography,0_Comedy,0_Crime,0_Drama,0_Family,0_Fantasy,0_Horror,...,2_Horror,2_Music,2_Musical,2_Mystery,2_Romance,2_Sci-Fi,2_Sport,2_Thriller,2_War,2_Western
original_title,,,,,,,,,,,,,,,,,,,,,
Along Came Polly,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Into the Woods,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The 5th Wave,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
The Wolverine,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Magic Mike,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wish I Was Here,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
After Earth,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Pet Sematary,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
Bohemian Rhapsody,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Begin Again,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [353]:
test_df = pd.DataFrame(sample_df.genre.str.split(', ').tolist(), index=sample_df.original_title).stack()
test_df

original_title
Along Came Polly   0       Comedy
                   1      Romance
Into the Woods     0    Adventure
                   1       Comedy
                   2        Drama
                          ...
Bohemian Rhapsody  1        Drama
                   2        Music
Begin Again        0       Comedy
                   1        Drama
                   2        Music
Length: 25872, dtype: object

In [354]:
test_df = test_df.reset_index([0,'original_title'])
test_df

          original_title          0
0       Along Came Polly     Comedy
1       Along Came Polly    Romance
2         Into the Woods  Adventure
3         Into the Woods     Comedy
4         Into the Woods      Drama
...                  ...        ...
25867  Bohemian Rhapsody      Drama
25868  Bohemian Rhapsody      Music
25869        Begin Again     Comedy
25870        Begin Again      Drama
25871        Begin Again      Music

[25872 rows x 2 columns]

In [355]:
test_df.columns = ['original_title', 'genre']
test_df

          original_title      genre
0       Along Came Polly     Comedy
1       Along Came Polly    Romance
2         Into the Woods  Adventure
3         Into the Woods     Comedy
4         Into the Woods      Drama
...                  ...        ...
25867  Bohemian Rhapsody      Drama
25868  Bohemian Rhapsody      Music
25869        Begin Again     Comedy
25870        Begin Again      Drama
25871        Begin Again      Music

[25872 rows x 2 columns]

In [356]:
dummy = pd.get_dummies(test_df, columns=['genre'])
dummy

,original_title,genre_Action,genre_Adventure,genre_Animation,genre_Biography,genre_Comedy,genre_Crime,genre_Drama,genre_Family,genre_Fantasy,...,genre_Horror,genre_Music,genre_Musical,genre_Mystery,genre_Romance,genre_Sci-Fi,genre_Sport,genre_Thriller,genre_War,genre_Western
0,Along Came Polly,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Along Came Polly,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,Into the Woods,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Into the Woods,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Into the Woods,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25867,Bohemian Rhapsody,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
25868,Bohemian Rhapsody,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25869,Begin Again,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25870,Begin Again,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
25871,Begin Again,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [357]:
dummy['original_title'].nunique()

3785

In [358]:
group_df = dummy.groupby(['original_title']).max()
group_df

,genre_Action,genre_Adventure,genre_Animation,genre_Biography,genre_Comedy,genre_Crime,genre_Drama,genre_Family,genre_Fantasy,genre_Film-Noir,...,genre_Horror,genre_Music,genre_Musical,genre_Mystery,genre_Romance,genre_Sci-Fi,genre_Sport,genre_Thriller,genre_War,genre_Western
original_title,,,,,,,,,,,,,,,,,,,,,
(500) Days of Summer,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
*batteries not included,0,0,0,0,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
10 Cloverfield Lane,1,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
10 Things I Hate About You,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
"10,000 BC",1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
xXx: Return of Xander Cage,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
xXx: State of the Union,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Â¡Three Amigos!,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Ã†on Flux,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [359]:
arr = test_df['genre'].unique()
genres = arr.tolist()
genres

['Comedy',
 'Romance',
 'Adventure',
 'Drama',
 'Action',
 'Sci-Fi',
 'Crime',
 'Mystery',
 'Horror',
 'Thriller',
 'Fantasy',
 'Biography',
 'Animation',
 'Family',
 'Music',
 'History',
 'Musical',
 'Sport',
 'War',
 'Western',
 'Film-Noir']